# Generated by Django 4.2.7 on 2023-12-16 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailerTemplate',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, help_text='Template identification number.', primary_key=True, serialize=False, verbose_name='Template ID')),
                ('active', models.BooleanField(db_column='active', default=True, help_text='Is the e-mail template active and available?', verbose_name='Active?')),
                ('name', models.CharField(db_column='name', help_text='Name of the e-mail template.', max_length=32, validators=[django.core.validators.MinLengthValidator(limit_value=1), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='Template Name')),
                ('description', models.TextField(blank=True, db_column='description', help_text='Description of the e-mail template.', verbose_name='Template Description')),
                ('subject', models.CharField(db_column='subject', help_text='Subject of e-mail message(s) sent using the template.', max_length=32, validators=[django.core.validators.MinLengthValidator(limit_value=1), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='E-mail Subject')),
                ('body', models.TextField(db_column='body', help_text='Body of e-mail message(s) sent using the template.', verbose_name='E-mail Body')),
            ],
            options={
                'verbose_name': 'Template',
                'db_table': 'templates',
                'managed': True,
            },
        ),
    ]
