# Generated by Django 4.2.7 on 2023-12-16 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailerMessage',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, help_text='Message identification number.', primary_key=True, serialize=False, verbose_name='Message ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Sent'), (1, 'Failed'), (2, 'Queued')], db_column='status', default=2, help_text='Status of the e-mail message.', verbose_name='Message Status')),
                ('recipient', models.EmailField(db_column='recipient', help_text='E-mail address of the recipient of the e-mail message.', max_length=254, verbose_name='E-mail Address')),
                ('subject', models.CharField(db_column='subject', help_text='Subject of the e-mail message.', max_length=32, validators=[django.core.validators.MinLengthValidator(limit_value=1), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='E-mail Subject')),
                ('body', models.TextField(db_column='body', help_text='Body of the e-mail message.', verbose_name='E-mail Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Date and time when the e-mail message was created.', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Message',
                'db_table': 'messages',
                'managed': True,
            },
        ),
    ]
