# Generated by Django 4.2.7 on 2023-12-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_mailermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailermessage',
            name='sent_at',
            field=models.DateTimeField(db_column='sent_at', default=None, editable=False, help_text='Date and time when the e-mail message was sent.', null=True, verbose_name='Sent At'),
        ),
    ]
