# Generated by Django 4.2.7 on 2023-12-17 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_mailermessage_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailerVariable',
            fields=[
                ('name', models.SlugField(db_column='name', help_text='Name of the variable to be made available to all templates.', primary_key=True, serialize=False, verbose_name='Name')),
                ('value', models.CharField(db_column='value', help_text='Value of the global e-mail template variable.', max_length=64, validators=[django.core.validators.MinLengthValidator(limit_value=1), django.core.validators.MaxLengthValidator(limit_value=64)], verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Variables',
                'db_table': 'variables',
                'managed': True,
            },
        ),
    ]
