# Generated by Django 4.2.7 on 2023-12-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_mailervariable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailervariable',
            options={'managed': True, 'verbose_name': 'Variable'},
        ),
    ]
