# Generated by Django 5.0 on 2023-12-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_alter_mailervariable_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailermessage',
            name='sender',
            field=models.EmailField(db_column='sender', default='djadmin@gaw.sh', help_text='E-mail address of the sender of the e-mail message.', max_length=254, verbose_name='Sender E-mail Address'),
        ),
        migrations.AddField(
            model_name='mailertemplate',
            name='sender',
            field=models.EmailField(db_column='sender', default='djadmin@gaw.sh', help_text='From address of e-mail message(s) sent using the template.', max_length=254, verbose_name='Sender E-mail Address'),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='recipient',
            field=models.EmailField(db_column='recipient', help_text='E-mail address of the recipient of the e-mail message.', max_length=254, verbose_name='Recipient E-mail Address'),
        ),
    ]
