# Generated by Django 5.0 on 2023-12-17 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_mailermessage_sender_mailertemplate_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailermessage',
            name='recipient',
            field=models.EmailField(db_column='recipient', help_text='E-mail address of the recipient of the e-mail message.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Recipient E-mail Address'),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='sender',
            field=models.EmailField(db_column='sender', default='djadmin@gaw.sh', help_text='E-mail address of the sender of the e-mail message.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Sender E-mail Address'),
        ),
        migrations.AlterField(
            model_name='mailertemplate',
            name='sender',
            field=models.EmailField(db_column='sender', default='djadmin@gaw.sh', help_text='From address of e-mail message(s) sent using the template.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Sender E-mail Address'),
        ),
    ]
