# Generated by Django 5.0 on 2023-12-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0008_alter_mailermessage_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailermessage',
            options={'managed': True, 'ordering': ('-sent_at', '-created_at', '-id'), 'verbose_name': 'Message'},
        ),
        migrations.AlterModelOptions(
            name='mailertemplate',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Template'},
        ),
        migrations.AlterModelOptions(
            name='mailervariable',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Variable'},
        ),
    ]
