# Generated by Django 5.0 on 2023-12-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0009_alter_mailermessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailermessage',
            options={'managed': True, 'ordering': ('-id',), 'verbose_name': 'Message'},
        ),
    ]
