# Generated by Django 5.0 on 2023-12-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0010_alter_mailermessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailervariable',
            name='value',
            field=models.TextField(db_column='value', help_text='Value of the global e-mail template variable.', verbose_name='Value'),
        ),
    ]
