# Generated by Django 5.0 on 2023-12-17 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0011_alter_mailervariable_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailermessage',
            name='recipient',
            field=models.EmailField(db_column='recipient', help_text='E-mail address of the recipient of the message.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Recipient E-mail Address'),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='sender',
            field=models.EmailField(db_column='sender', default='djadmin@gaw.sh', help_text='E-mail address of the sender of the message.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Sender E-mail Address'),
        ),
        migrations.AlterField(
            model_name='mailermessage',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Sent'), (1, 'Failed'), (2, 'Queued'), (3, 'Canceled')], db_column='status', default=2, help_text='Status of the e-mail message.', verbose_name='Status'),
        ),
    ]
