# Generated by Django 5.0 on 2023-12-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widgetuser',
            options={'default_related_name': 'user', 'managed': True, 'ordering': ('username',), 'verbose_name': 'User'},
        ),
    ]
