# Generated by Django 4.2.7 on 2023-12-10 21:32

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import mailmod.fields
import mailmod.settings
import mailmod.utils
import mailmod.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Template name')),
                ('description', models.TextField(blank=True, verbose_name='Template description')),
                ('subject', models.CharField(max_length=254, validators=[mailmod.validators.validate_template_syntax], verbose_name='Subject')),
                ('email_html_text', models.TextField(blank=True, validators=[mailmod.validators.validate_template_syntax], verbose_name='Email html text')),
            ],
            options={
                'verbose_name': 'Email template',
                'verbose_name_plural': 'Email templates',
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='EMAIL_USE_TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='EMAIL_USE_SSL')),
                ('email_ssl_keyfile', models.CharField(blank=True, max_length=1024, null=True, verbose_name='EMAIL_SSL_KEYFILE')),
                ('email_ssl_certfile', models.CharField(blank=True, max_length=1024, null=True, verbose_name='EMAIL_SSL_CERTFILE')),
                ('email_host', models.CharField(max_length=1024, verbose_name='EMAIL_HOST')),
                ('email_host_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL_HOST_USER')),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL_HOST_PASSWORD')),
                ('email_port', models.PositiveSmallIntegerField(default=25, verbose_name='EMAIL_PORT')),
                ('email_timeout', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='EMAIL_TIMEOUT')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Outbox',
                'verbose_name_plural': 'Outboxes',
            },
        ),
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=254, validators=[mailmod.validators.validate_email_with_name], verbose_name='From email')),
                ('to', mailmod.fields.CommaSeparatedEmailField(blank=True, verbose_name='To email(s)')),
                ('cc', mailmod.fields.CommaSeparatedEmailField(blank=True, verbose_name='Cc')),
                ('bcc', mailmod.fields.CommaSeparatedEmailField(blank=True, verbose_name='Bcc')),
                ('subject', models.CharField(blank=True, max_length=989, verbose_name='Subject')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('html_message', models.TextField(blank=True, help_text='Used only if template is not selected', verbose_name='HTML Message')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('scheduled_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='The scheduled sending time')),
                ('headers', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Headers')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'sent'), (1, 'failed'), (2, 'queued')], db_index=True, null=True, verbose_name='Status')),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'low'), (1, 'medium'), (2, 'high'), (3, 'now')], null=True, verbose_name='Priority')),
                ('send_now', models.BooleanField(default=False, verbose_name='Send now')),
                ('backend_alias', models.CharField(blank=True, default='', help_text=mailmod.settings.get_backend_names_str, max_length=64, verbose_name='Backend alias')),
                ('template', models.ForeignKey(blank=True, help_text='If template is selected, HTML message and subject fields will notbe used - they will be populated from template', null=True, on_delete=django.db.models.deletion.CASCADE, to='mailmod.emailtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Outgoing email',
                'verbose_name_plural': 'Outgoing emails',
            },
        ),
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Variable name')),
                ('value', models.TextField(blank=True, verbose_name='Variable value')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailmod.outgoingemail')),
            ],
            options={
                'verbose_name': 'Template variable',
                'verbose_name_plural': 'Template variables',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'sent'), (1, 'failed')], verbose_name='Status')),
                ('exception_type', models.CharField(blank=True, max_length=255, verbose_name='Exception type')),
                ('message', models.TextField(verbose_name='Message')),
                ('email', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailmod.outgoingemail', verbose_name='Email address')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mailmod.utils.get_attachment_save_path, verbose_name='File')),
                ('name', models.CharField(help_text='The original filename', max_length=255, verbose_name='Name')),
                ('mimetype', models.CharField(blank=True, default='', max_length=255)),
                ('emails', models.ManyToManyField(blank=True, related_name='attachments', to='mailmod.outgoingemail', verbose_name='Email addresses')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
