# Generated by Django 4.2.7 on 2023-12-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailmod', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outbox',
        ),
    ]
