# Generated by Django 5.1.6 on 2025-02-26 03:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, help_text='Widget identification number.', primary_key=True, serialize=False, verbose_name='Widget ID')),
                ('name', models.SlugField(db_column='name', help_text='Name of the widget.', max_length=32, validators=[django.core.validators.MinLengthValidator(limit_value=2), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='Widget Name')),
                ('description', models.TextField(blank=True, db_column='description', help_text='Description of the widget.', verbose_name='Widget Description')),
                ('active', models.BooleanField(db_column='active', default=True, help_text='Is the widget active and available?', verbose_name='Active?')),
                ('email', models.EmailField(blank=True, db_column='email', default=None, help_text='E-mail address for widget notifications.', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Date and time when the widget was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=None, editable=False, help_text='Date and time when the widget was last updated.', null=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(db_column='created_by', editable=False, help_text='User who created the widget.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(db_column='template', default=None, help_text='E-mail template to be used for for widget notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.mailertemplate', verbose_name='E-mail Template')),
                ('updated_by', models.ForeignKey(db_column='updated_by', default=None, editable=False, help_text='User who last updated the widget.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Widget',
                'db_table': 'widgets',
                'ordering': ('name',),
                'managed': True,
            },
        ),
    ]
