# Generated by Django 5.0.2 on 2024-02-26 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailermessage',
            name='from_name',
            field=models.CharField(blank=True, db_column='from_name', help_text='Sender name in the e-mail "From" address.', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=1), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='From Name'),
        ),
        migrations.AddField(
            model_name='mailertemplate',
            name='from_name',
            field=models.CharField(blank=True, db_column='from_name', help_text='From name of e-mail message(s) sent using the template.', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=1), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='From Name'),
        ),
    ]
