# Generated by Django 5.0.2 on 2024-02-26 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_mailermessage_from_name_mailertemplate_from_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailermessage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='mailermessage',
            name='reply_to_address',
        ),
        migrations.RemoveField(
            model_name='mailermessage',
            name='to_address',
        ),
        migrations.RemoveField(
            model_name='mailertemplate',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='mailertemplate',
            name='reply_to_address',
        ),
        migrations.AddField(
            model_name='mailermessage',
            name='from_email',
            field=models.EmailField(db_column='from_email', default='djadmin@gaw.sh', help_text='Sender ("From") e-mail address of the message.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='From E-mail Address'),
        ),
        migrations.AddField(
            model_name='mailermessage',
            name='reply_to_email',
            field=models.EmailField(db_column='reply_to_email', default='djadmin@gaw.sh', help_text='"Reply-To" e-mail address of the message.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Reply-To E-mail Address'),
        ),
        migrations.AddField(
            model_name='mailermessage',
            name='reply_to_name',
            field=models.CharField(blank=True, db_column='reply_to_name', help_text='Reply-To name of the message.', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=1), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='From Name'),
        ),
        migrations.AddField(
            model_name='mailermessage',
            name='to_email',
            field=models.EmailField(db_column='to_email', default='eric@ericoc.com', help_text='Primary ("To") recipient e-mail address of the message.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Recipient E-mail Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailermessage',
            name='to_name',
            field=models.CharField(blank=True, db_column='to_name', help_text='Recipient name in the e-mail "To" address.', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=1), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='Recipient Name'),
        ),
        migrations.AddField(
            model_name='mailertemplate',
            name='from_email',
            field=models.EmailField(db_column='from_email', default='djadmin@gaw.sh', help_text='From address of e-mail message(s) sent using the template.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Sender E-mail Address'),
        ),
        migrations.AddField(
            model_name='mailertemplate',
            name='reply_to_email',
            field=models.EmailField(db_column='reply_to_email', default='djadmin@gaw.sh', help_text='Reply-To e-mail address of message(s) sent using the template.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Reply-To E-mail Address'),
        ),
        migrations.AddField(
            model_name='mailertemplate',
            name='reply_to_name',
            field=models.CharField(blank=True, db_column='reply_to_name', help_text='Reply-To e-mail name of message(s) sent using the template.', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=1), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='Reply-To Name'),
        ),
    ]
