# Generated by Django 5.0.2 on 2024-02-26 01:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_remove_mailermessage_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailerrecipient',
            name='name',
            field=models.CharField(blank=True, db_column='name', default=None, help_text='Recipient Name', max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=1), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='Recipient Name'),
        ),
        migrations.AlterField(
            model_name='mailerrecipient',
            name='message',
            field=models.ForeignKey(db_column='message', help_text='Message related to the recipient.', on_delete=django.db.models.deletion.CASCADE, to='mailer.mailermessage', verbose_name='Message'),
        ),
    ]
