# Generated by Django 4.2.7 on 2023-12-09 04:24

from django.db import migrations, models
import django.db.models.deletion
import django_mail_admin_mod.fields
import django_mail_admin_mod.settings
import django_mail_admin_mod.utils
import django_mail_admin_mod.validators
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Template Description')),
                ('subject', models.CharField(max_length=254, validators=[django_mail_admin_mod.validators.validate_template_syntax], verbose_name='Subject')),
                ('email_html_text', models.TextField(blank=True, validators=[django_mail_admin_mod.validators.validate_template_syntax], verbose_name='Email HTML Text')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='EMAIL_USE_TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='EMAIL_USE_SSL')),
                ('email_ssl_keyfile', models.CharField(blank=True, max_length=1024, null=True, verbose_name='EMAIL_SSL_KEYFILE')),
                ('email_ssl_certfile', models.CharField(blank=True, max_length=1024, null=True, verbose_name='EMAIL_SSL_CERTFILE')),
                ('email_host', models.CharField(max_length=1024, verbose_name='EMAIL_HOST')),
                ('email_host_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL_HOST_USER')),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL_HOST_PASSWORD')),
                ('email_port', models.PositiveSmallIntegerField(default=25, verbose_name='EMAIL_PORT')),
                ('email_timeout', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='EMAIL_TIMEOUT')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Outbox',
                'verbose_name_plural': 'Outboxes',
            },
        ),
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=254, validators=[django_mail_admin_mod.validators.validate_email_with_name], verbose_name='From E-mail Address')),
                ('to', django_mail_admin_mod.fields.CommaSeparatedEmailField(blank=True, verbose_name='To E-mail Address(es)')),
                ('cc', django_mail_admin_mod.fields.CommaSeparatedEmailField(blank=True, verbose_name='CC')),
                ('bcc', django_mail_admin_mod.fields.CommaSeparatedEmailField(blank=True, verbose_name='BCC')),
                ('subject', models.CharField(blank=True, max_length=989, verbose_name='Subject')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('html_message', models.TextField(blank=True, help_text='Used only if template is not selected.', verbose_name='HTML Message')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('scheduled_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled Send Time')),
                ('headers', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Headers')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'sent'), (1, 'failed'), (2, 'queued')], db_index=True, null=True, verbose_name='Status')),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'low'), (1, 'medium'), (2, 'high'), (3, 'now')], null=True, verbose_name='Priority')),
                ('send_now', models.BooleanField(default=False, verbose_name='Send Now')),
                ('backend_alias', models.CharField(blank=True, default='', help_text=django_mail_admin_mod.settings.get_backend_names_str, max_length=64, verbose_name='Backend Alias')),
                ('template', models.ForeignKey(blank=True, help_text='If template is selected, HTML message and subject fields will not be used - they will be populated from template', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_mail_admin_mod.emailtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Outgoing E-mail',
                'verbose_name_plural': 'Outgoing E-mails',
            },
        ),
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Variable Name')),
                ('value', models.TextField(blank=True, verbose_name='Variable Value')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_mail_admin_mod.outgoingemail')),
            ],
            options={
                'verbose_name': 'Template Variable',
                'verbose_name_plural': 'Template Variables',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'sent'), (1, 'failed')], verbose_name='Status')),
                ('exception_type', models.CharField(blank=True, max_length=255, verbose_name='Exception Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('email', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='django_mail_admin_mod.outgoingemail', verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=django_mail_admin_mod.utils.get_attachment_save_path, verbose_name='File')),
                ('name', models.CharField(help_text='The original filename.', max_length=255, verbose_name='Name')),
                ('mimetype', models.CharField(blank=True, default='', max_length=255)),
                ('emails', models.ManyToManyField(blank=True, related_name='attachments', to='django_mail_admin_mod.outgoingemail', verbose_name='Email addresses')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
