# Generated by Django 4.2.7 on 2023-11-30 23:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, help_text='Widget identification number.', primary_key=True, serialize=False, verbose_name='Widget ID')),
                ('name', models.SlugField(help_text='Name of the widget.', max_length=64, validators=[django.core.validators.MinLengthValidator(limit_value=2), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='Widget Name')),
                ('description', models.TextField(blank=True, db_column='description', help_text='Description of the widget.', verbose_name='Widget Description')),
                ('active', models.BooleanField(default=True, help_text='Is the widget active and available?', verbose_name='Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Date and time when the widget was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=None, editable=False, help_text='Date and time when the widget was last updated.', null=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(db_column='created_by', editable=False, help_text='User who created the widget.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(db_column='updated_by', default=None, editable=False, help_text='User who last updated the widget.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Widget',
                'db_table': 'widgets',
                'managed': True,
            },
        ),
    ]
