# Generated by Django 4.2.7 on 2023-12-16 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='active',
            field=models.BooleanField(db_column='active', default=True, help_text='Is the widget active and available?', verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.SlugField(db_column='name', help_text='Name of the widget.', max_length=32, validators=[django.core.validators.MinLengthValidator(limit_value=2), django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='Widget Name'),
        ),
    ]
