# Generated by Django 4.2.7 on 2023-12-01 00:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetComment',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, help_text='Widget comment identification number.', primary_key=True, serialize=False, verbose_name='Widget Comment ID')),
                ('text', models.TextField(blank=True, db_column='text', help_text='Text of the widget comment.', max_length=256, validators=[django.core.validators.MaxLengthValidator(limit_value=256)], verbose_name='Widget Comment Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Date and time when the widget comment was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=None, editable=False, help_text='Date and time when the widget comment was last updated.', null=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(db_column='created_by', editable=False, help_text='User who created the widget comment.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('widget', models.ForeignKey(db_column='widget', editable=False, help_text='Widget related to the comment.', on_delete=django.db.models.deletion.PROTECT, to='widgets.widget', verbose_name='Widget')),
            ],
            options={
                'verbose_name': 'Comment',
                'db_table': 'widget_comments',
                'managed': True,
                'default_related_name': 'comment',
            },
        ),
    ]
