# Generated by Django 4.2.7 on 2023-12-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
        ('widgets', '0002_alter_widget_active_alter_widget_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='template',
            field=models.ForeignKey(db_column='template', default=None, help_text='E-mail template to be used for for widget notifications.', null=True, on_delete=django.db.models.deletion.PROTECT, to='mailer.mailertemplate', verbose_name='E-mail Template'),
        ),
    ]
