# Generated by Django 4.2.7 on 2023-12-01 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('widgets', '0002_widgetcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetcomment',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', editable=False, help_text='User who created the widget comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterUniqueTogether(
            name='widgetcomment',
            unique_together={('created_by', 'widget')},
        ),
    ]
