# Generated by Django 5.0 on 2023-12-17 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_widget_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='email',
            field=models.EmailField(blank=True, db_column='email', default=None, help_text='E-mail address for widget notifications.', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail Address'),
        ),
    ]
