# Generated by Django 4.2.7 on 2023-12-08 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mail_admin', '0002_auto_20190709_1139'),
        ('widgets', '0003_alter_widgetcomment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_mail_admin.emailtemplate'),
        ),
    ]
