# Generated by Django 4.2.7 on 2023-12-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0004_widget_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='email',
            field=models.EmailField(blank=True, db_column='email', default=None, help_text='E-mail address for widget notifications.', max_length=254, null=True, verbose_name='E-mail Address'),
        ),
    ]
