# Generated by Django 5.0 on 2023-12-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0004_alter_widget_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'managed': True, 'ordering': ('-updated_at', '-created_at', '-id'), 'verbose_name': 'Widget'},
        ),
        migrations.AlterModelOptions(
            name='widgetcomment',
            options={'default_related_name': 'comment', 'managed': True, 'ordering': ('-updated_at', '-created_at', '-id'), 'verbose_name': 'Comment'},
        ),
    ]
