# Generated by Django 5.0 on 2023-12-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0005_alter_widget_options_alter_widgetcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'managed': True, 'ordering': ('-id',), 'verbose_name': 'Widget'},
        ),
    ]
