# Generated by Django 5.0 on 2023-12-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0006_alter_widget_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Widget'},
        ),
    ]
