# Generated by Django 5.0 on 2023-12-17 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0007_alter_widget_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetcomment',
            name='widget',
            field=models.ForeignKey(db_column='widget', editable=False, help_text='Widget related to the comment.', on_delete=django.db.models.deletion.PROTECT, related_name='comments', related_query_name='comment', to='widgets.widget', verbose_name='Widget'),
        ),
    ]
