# Generated by Django 5.0 on 2023-12-17 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0008_alter_widgetcomment_widget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetcomment',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, editable=False, help_text='User who created the widget comment.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
            preserve_default=False,
        ),
    ]
